let soul = [
'Don’t worry when you are not recognized, but strive to be worthy of recognition.如果不被别人认可，不要担心，要努力让自己值得被认可。',
'When you have exhausted all possibilities, remember this: you haven’t.当你已穷尽所有可能性时，要记住：还是有可能。',
'Keep your face always toward the sunshine—and shadows will fall behind you.总是面向阳光,阴影就会被甩在身后。',
'The power of imagination makes us infinite.想象力让我们突破极限。',
'The world is full of magical things patiently waiting for our wits to grow sharper.世界充满了神奇的东西，它们在耐心地等待我们变得更有智慧。',
'The glow of one warm thought is to me worth more than money.温暖的想法散发出的光辉,对我的价值胜过金钱。',
'Let us make our future now, and let us make our dreams tomorrow’s reality.即刻起，为未来奋斗，要让今天的梦想成为明天的现实。',
'All you need is the plan, the road map, and the courage to press on to your destination.你只需要订好计划，准备好地图，鼓起向目标前进的勇气。',
'It is always the simple that produces the marvelous.大道至简。',
'Try to be a rainbow in someone’s cloud.试着成为别人天空里的那道彩虹吧。',
'I believe that if one always looked at the skies, one would end up with wings.我坚信,总是仰望天空的人,最终一定会展翅高飞。',
'Light tomorrow with today.用现在点亮未来。',
'I arise full of eagerness and energy, knowing well what achievement lies ahead of me.我站起身来,满怀期盼,振奋不已,因为我很明白,成功就在前方。',
'A No. 2 pencil and a dream can take you anywhere.一2号铅笔，一个梦想，就能带你去任何你想去的地方。',
'When the sun is shining I can do anything; no mountain is too high, no trouble too difficult to overcome.只要阳光普照，一切我都可以做到；没有翻不过的高山，没有战胜不了的困难。',
'Happiness is not something you postpone for the future; it is something you design for the present.幸福不应该等到未来去拥有，而是为了当下所准备。',
'No man or woman is worth your tears, and the one who is, won’t make you cry.没有人值得你流泪，值得让你这么做的人不会让你哭泣。',
'Life is ten percent what you make it and ninety percent how you take it.生活有百分之十在于你如何塑造它，有百分之九十在于你如何对待它。',
'And in the end, it’s not the years in your life that count. It’s the life in your years.最终真正重要的不是你生命的岁月，而是你岁月中的生命。',
'There is no cure for birth and death save to enjoy the interval.生与死没有解药，所以只能在生死之间去享受生活。',
'Follow your bliss and the universe will open doors where there were only walls.跟从你的快乐，宇宙就会在原本只有墙的地方为你敞开大门。',
'The furthest way about is the nearest way home.欲速则不达。',
'四月间，天气寒冷晴朗，钟敲了十三下。It was a bright cold day in April, and the clocks were striking thirteen.- George Orwell',
'生命太短暂了,不应该用来记恨,人生在世,谁都会有错误。Life appears to me too short to be spent in nursing animosity or registering wrongs." - Jane Eyre  Charlotte Brontë',
'你忘了你想要牢记的,但你却牢记了你想要忘却的。You forget what you want to remember, and you remember what you want to forget.- The Road Cormac McCarthy',
'回忆温暖了你的内心。但是，他们也把你撕裂。Memories warm you up from the inside. But they also tear you apart.- Kafka on the Shore Haruki Murakami',
'“历史，”斯蒂芬说，“是一场噩梦，我试图清醒。”History, Stephen said, is a nightmare from which I am trying to awake.- Ulysses  James Joyce',
'于是我们奋力向前划，逆流向上的小舟，不停地倒退，进入过去。So we beat on, boats against the current, borne back ceaselessly into the past.- The Great Gatsby',
'如今人们对每样东西的价格了如指掌,对它们的价值却一无所知。Nowadays people know the price of everything and the value of nothing.- The Picture Of Dorian Gray   Oscar Wilde',
'真相一直都在，Frank，人们只是变得更会说谎。No one forgets the truth; they just get better at lying."- Revolutionary Road  Richard Yates',
'对于人来说，没有什么比巨变更痛苦。Nothing is so painful to the human mind as a great and sudden change.- Frankenstein Mary Shelley',
'有时现实如此糟糕，我们除了疯掉无路可走。It is sometimes an appropriate response to reality to go insane.- Valis  Philip K. Dick',
'我知道，我在那儿。我看到你灵魂中巨大的空虚，也也看穿了我的。I know. I was there. I saw the great void in your soul, and you saw mine.- Birdsong   Sebastian Faulks',
'Miracles sometimes occur, but one has to work terribly for them. 奇迹有时候是会发生的，但是你得为之拼命的努力。—C. Weizmann（爱尔兰总统魏茨曼）　　　　',
'It never will rain roses.When we want to have more roses we must plant trees. 天上不会掉下玫瑰来，如果想要更多的玫瑰，必须自己种植。—G. Eliot（英国小说家艾略特）　　　　',
'Great works are performed not by strength , but by perseverance. 完成伟大的事业不在于体力，而在于坚韧不拔的毅力。—Samuel Johnson（英国作家和评论家约翰逊）　　　　',
'Genius only means hard-working all one’s life. 天才只意味着终身不懈的努力。—Mendeleyev（俄国化学家门捷列耶夫）　　　　',
'The only limit to our realization of tomorrow will be our doubts of today.实现明天理想的唯一障碍是今天的疑虑。—Franklin Roosevelt（美国总统罗斯福）',
'Do not, for one repulse,give up the purpose that you resolved to effect.不要只因一次失败，就放弃你原来决心想要达到的目的。—Willian Shakespeare（莎士比亚）',
'You have to believe in yourself. That’s the secret of success. 你必须相信自己，这是成功的关键。—Charles Chaplin（美国演员卓别林）　　　　',
'A man can succeed at almost anything for which he has unlimited enthusiasm. 无论何事，只要对它有无限的热情你就能取得成功。—C. M. Schwab（美国实业家施瓦布）',
'To be trusted is a greater compliment than to be loved.---被人信任，是比被人喜爱还要更大的赞许。',
'There’s nothing more beautiful than a smile that struggles through tears.---世上最美的，莫过于从泪水中挣脱出来的那个微笑。',
'Don’t know whether the next life can meet, so this life want to give you his best.---不知道下辈子是否还能遇见，所以今生想把自己最好的都给你。',
'No one can defeat us unless we first defeat ourselves.---在这个世界上，除了那个不争气的自己，再也没有人能阻止你变得更好。',
'Low-key man you will each time the steady，high-profile do things you will each time---低调做人你会一次比一次稳健，高调做事你会一次比一次优秀。',
'Some love, can only stop at the lips and teeth, mask in the years to come.---至少在属于我出场的时间里，曾拼尽全力爱过你。',
'Distance doesn’t bring beauty but explains the fragile love.---距离，产生的不是美，而是诠释了不堪一击的爱情。',
'It is not about me not caring - what is the difference whether I care or not.---有些事情不是我不在意，而是我在意了又能怎样。',
'A game is always popular between the people, that is "lose once you get serious"---人和人之间都很喜欢玩一个历久不衰的游戏，叫“你一认真你就输了”。',
'There is a time in life that is full of uneasiness.We have no other choice but to face it.---生命中总有那么一段时光，充满不安，可是除了勇敢面对，我们别无选择。',
'Love is so hard but I want you to try.---相爱太难 但我想和你试试',
'Do not, for one repulse, forget the purpose that you resolved to effort.---不要只因一次挫折，就忘记你原先想要努力到达的远方。',
'Can’t get preference in turmoil, was forever have no fear hold.---得不到的永远在骚动，被偏爱的都有持无恐。',
'Sometimes you need to be alone, in order to find out who you really are and what you really want.---有时候你需要独处，只为了找到真正的自己和自己真正想要的。',
'When you can digest a person silently when negative emotions, you are really grown up。---当你能一个人默默消化掉负面情绪的时候，你就真的长大了。',
'Life can be wandering, can be lonely, but your soul has to be a refuge.--- 生活可以漂泊，可以孤独，但你的灵魂必须有所归依。',
'Trust is the easiest thing in the world to lose，and the hardest thing in the world to get back.--- 信任是这个世界上最容易失去的东西，也是最难挽回的东西。',
'We’ve sticked for a long time but finally defeated by eternity.---我们撑了好久，最后输给了天长地久。',
'If you leave me, please don’t comfort me because each sewing has to meet stinging pain.---离开我就别安慰我，要知道每一次缝补也会遭遇穿刺的痛。',
'Ordinary accompany the most reassuring, know you are the most warm .---平凡的陪伴最心安，懂你的人最温暖',
'Happy is looks for a warm person for a lifetime---幸福，就是找一个温暖的人过一辈子',
'Love me little， love me long.---爱不贵亲密，而贵长久。',
'Crouch down, hold your knees when you are depressed.Forgive others and yourself.---郁闷的时候蹲下来抱抱自己，原谅别人也原谅自己',
'Active long will be very tired, care about for a long time will crash!---主动久了会很累， 在乎久了会崩溃！',
'I will be better, because of you, but not for you.---我会变得更好，因为你，但不是为了你',
'I don’t what vows of eternal love I want you to accompany me through each spring, summer, autumn and winter.---我不要什么海誓山盟 我只要你陪我走过每个春夏秋冬。',
'If I say leave me alone , actually I need you more than anytime.---如果我说我想一个人静一静，其实我比任何时候都需要你。',
'Sometimes it is better to be alone. Nobody can hurt you.---有时候，孤单一个人反而更好，没人伤害得了你',
];

function randomSentence() {
  document.getElementById('sentence').innerHTML = soul[Math.floor(Math.random() * soul.length)];
}



randomSentence();
